name: relcheck-action
description: Downloads, caches, and runs relcheck with verbose output on files tracked by Git.
branding:
  icon: check
  color: green
inputs:
  version:
    description: relcheck version in semver format without the 'v' prefix
    required: false
    default: "1.8.12"
  install-path:
    description: Installation path without trailing slash for the binary
    required: false
    default: /usr/local/bin
runs:
  using: "composite"
  steps:
    - name: Convert architecture
      id: arch
      shell: sh
      env:
        runner_arch: ${{ runner.arch }} # Possible values are X86, X64, ARM, or ARM64.
      run: |
        case "$runner_arch" in
          X64) echo "arch=amd64" >> "$GITHUB_OUTPUT" ;;
          ARM64) echo "arch=arm64" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported architecture: $runner_arch" >&2; exit 1 ;;
        esac
    - name: Convert OS
      id: os
      shell: sh
      env:
        runner_os: ${{ runner.os }} # Possible values are Linux, Windows, or macOS.
      run: |
        case "$runner_os" in
          Linux) echo "os=linux" >> "$GITHUB_OUTPUT" ;;
          macOS) echo "os=darwin" >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported OS: $runner_os" >&2; exit 1 ;;
        esac
    - name: Cache
      id: cache
      uses: actions/cache@v5
      with:
        path: ${{ inputs.install-path }}/relcheck
        key: relcheck-v${{ inputs.version }}-${{ steps.os.outputs.os }}-${{ steps.arch.outputs.arch }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      working-directory: ${{ runner.temp }}
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        version: ${{ inputs.version }}
        pattern: "relcheck-${{ steps.os.outputs.os }}-${{ steps.arch.outputs.arch }}.tar.gz"
        output: ${{ inputs.install-path }}/relcheck
      run: |
        echo "gh release download \"v$version\" --repo anttiharju/relcheck --pattern \"$pattern\""
        gh release download "v$version" --repo anttiharju/relcheck --pattern "$pattern"

        echo "tar -xzf \"$pattern\""
        tar -xzf "$pattern"

        echo "mv relcheck \"$output\""
        mv relcheck "$output"
    - shell: sh
      run: |
        relcheck all --verbose --color=always
