name: relcheck
description: Runs relcheck on default settings

runs:
  using: "composite"
  steps:
    - name: Decide which way to run
      id: decide
      shell: sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        if [ -f relcheck ]; then
          echo "Using local relcheck"
          echo "relcheck=local" >> "$GITHUB_OUTPUT"
        else
          echo "Using relcheck from anttiharju/actions/relcheck@v1"
          echo "relcheck=remote" >> "$GITHUB_OUTPUT"
        fi
        echo "version=$(gh release view --repo anttiharju/relcheck --json name --jq .name)" >> "$GITHUB_OUTPUT"
    - if: steps.decide.outputs.relcheck == 'remote'
      name: relcheck
      uses: anttiharju/actions/relcheck@v1
      with:
        version: ${{ steps.decide.outputs.version }}
    - if: steps.decide.outputs.relcheck == 'local'
      name: relcheck
      shell: sh
      run: ./relcheck all --verbose --color=always
