permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - "internal/**/*"
      - "*.go"
      - "go.*"
      # relcheck-specific:
      - "tests/**/*"
      - "test.sh"

jobs:
  wildcard:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          true
